compressor.exe: main.c node.c node_vector.c word_vector.c huffman.c encode.c decode.c
	cc main.c node.c node_vector.c word_vector.c huffman.c encode.c decode.c -o compressor.exe


debug: main.c node.c node_vector.c word_vector.c huffman.c encode.c decode.c
	cc -ggdb main.c node.c node_vector.c word_vector.c huffman.c encode.c decode.c -o compressor.exe
