#ifndef ERROR_CODES_H
#define ERROR_CODES_H


#define ERROR_MEMORY_ALLOC 1
#define ERROR_READING_FILE 2
#define ERROR_WRITING_FILE 3
#define ERROR_INVALID_PARAMETERS 4
#define ERROR_INVALID_FILE_FORMAT 5


#endif